# Random ------------------------------------------- #
    skins.1     =   100 101 102

# -------------------------------------------------- #
# Variants
#   100 - Vanilla
#   101 - Dark
#   102 - Red