skins.1=99
name.1=ipattern:*Maffhew*

skins.2=98
name.2=ipattern:*GrandPappyJay*

skins.3=7
name.3=ipattern:*Florist*

skins.4=8
name.4=ipattern:*Princess*

#snow
skins.5=100-103
biomes.5=snowy_taiga snowy_plains snowy_slopes ice_spikes snowy_beach jagged_peaks frozen_peaks frozen_ocean deep_frozen_ocean frozen_river grove

#pale
skins.6=900-903 999
biomes.6=pale_garden
weights.6=10 10 10 10 1

#catchall
skins.7=  1 2 3 4 5 6 7 92 93 94 95 96 97
weights.7=4 4 4 4 4 4 1 1  1  1  2  2  2

#legend
99 Maffhew
98 GrandPappyJay
97 Craig
96 Ruseki
95 lwkysad
94 Starlezz_
93 Ansen
92 FionaDanger
